### ISSUE TITLE
GetStuffIn.java seems to be all commented out for no apparent reason.

### ISSUE THREAD

**Issue by Darklight-03** [Team5427/robotics-code-2016#4]
Is there a reason you commented out all of the important parts of the command rather than just commenting out the line that ran the command? or a reason it was commented out at all?

**Comment by varshak314** [comment]
I'll need to look at code later o see what the reference is to. I probably just forgot to uncomment something, but not sure. Get stuff In works with the Intake via relay

**Comment by varshak314** [comment]
I mean, the Intake motor on the robot is run via relay. Don't know if that could be the reason. Will look later
